### PR TITLE
fix: fix-segment-builds

### PR DESCRIPTION
**Pull request by JasonPowr**
Testing to see if I can fix the builds for this on konflux.
Found this solution:  https://stackoverflow.com/questions/77605507/getting-requirements-to-build-wheel-did-not-run-successfully-what-am-i-doing

### CODE REVIEW

**Comment by JasonPowr** [comment]
Don't merge this untill @Gregory-Pereira has had a chance to review it pls

**Comment by JasonPowr** [comment]
> I get the same issues here:
> 
> ```
> pip_find_builddeps requirements.txt \
> --append \
> --only-write-on-update \
> -o requirements-build.in
> INFO: Please make sure the input files meet the requirements of this script (see --help)
> INFO: Running pip download, this may take a while
> ERROR: Pip download failed, see /var/folders/v4/6899pgpd34q1y_nzyg6350nm0000gn/T/pip_find_builddeps.py-ayh9pilz/pip-download-output.txt for more info
> $ cat /var/folders/v4/6899pgpd34q1y_nzyg6350nm0000gn/T/pip_find_builddeps.py-ayh9pilz/pip-download-output.txt
>  writing lib/PyYAML.egg-info/PKG-INFO
>   writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
>   writing top-level names to lib/PyYAML.egg-info/top_level.txt
>   Traceback (most recent call last):
>   ... (rest of stacktrace)
> ```
> 
> For some reason this process only uses wheels and there isnt a wheel available for that library

Ah Damn that's unfortunate, when it built in konflux I thought I fixed it, aplogies

**Comment by Gregory-Pereira** [comment]
It could be, I am running on arm64 darwin but it will be built in knflux in amd64 anylinux which I am testing now

**Pull request merged**
