### PR TITLE
pull in the library

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
/cc @lance @ppecka

### CODE REVIEW

**Comment by ppecka** [comment]
Greg I'm no use here. @bouskaJ Please check the MR

**Review by lance — APPROVED** [review]
I cannot believe it but OK lol

**Comment by Gregory-Pereira** [comment]
I have a local build of this at: quay.io/grpereir/segment-backup-job@sha256:d6447bc916a9ccb05f20b87bd66fd622f1c385c53c2df246eb910d69f529a831 for `amd64` architecture. Will be testing with that for the meantime

**Pull request merged**
