### PR TITLE
fix: dont-query-secrets

### PR DESCRIPTION
**Pull request by JasonPowr**
Changes the script to, use the bearer token of the service account used to run the SBJ pod.

CC: @tommyd450 @osmman @lance @Gregory-Pereira

### CODE REVIEW

**Review by osmman — APPROVED** [review]

**Review by lance — COMMENTED** [review]
/lgtm

**Comment by Gregory-Pereira** [comment]
IF you want to go this strategy of mounting the token to the pod via the SA, you need to add it to the SA spec as a secret, in the [operator code](https://github.com/securesign/secure-sign-operator/blob/main/controllers/securesign/actions/rbac.go#L58), there is an example of this here in the [k8s docs](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#auto-generated-legacy-serviceaccount-token-clean-up)

**Comment by JasonPowr** [comment]
@Gregory-Pereira I don't believe we need to mount the bearer-token as a secret for the SA, we don't need to use the token outside of this pod, all communication is done inside the pod. So it can just be passed to the function using it.

https://www.ibm.com/docs/en/cloud-private/3.2.x?topic=kubectl-using-service-account-tokens-connect-api-server#pod

@osmman WDYT?

**Comment by osmman** [comment]
> @Gregory-Pereira I don't believe we need to mount the bearer-token as a secret for the SA, we don't need to use the token outside of this pod, all communication is done inside the pod. So it can just be passed to the function using it.
> 
> https://www.ibm.com/docs/en/cloud-private/3.2.x?topic=kubectl-using-service-account-tokens-connect-api-server#pod
> 
> @osmman WDYT?

you are correct. The service accounts token is automatically mounted to pod by [serviceaccount admission controller](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#serviceaccount-admission-controller) and I expect that it is same token which is used by python kubernetes client used in SBJ.

**Review by Gregory-Pereira — APPROVED** [review]
Yeah all this checks out. Sorry for my misunderstandings, after meeting with Jason to understand the changes and re-review ing this gets my conceptual approval. I have not tested it but If you can vouch that it works as intended, I am happy with the direction of the pr.
/lgtm

**Pull request merged**
