### PR TITLE
update base images

### PR DESCRIPTION
**Pull request by JasonPowr**
updating base images

### CODE REVIEW

**Comment by JasonPowr** [comment]
/hold
dont merge this, testing stuff related to the CVE's that a produced in konflux

**Comment by lance** [comment]
Curious why not to merge it - it's definitely needed

**Comment by JasonPowr** [comment]
> Curious why not to merge it - it's definitely needed

Sorry yea this can be merged, my comment was more related to the fact that it doesn't fix the cve's showing up in konflux,  from what I can tell most seem to be coming from packages used in the oc binary

**Comment by JasonPowr** [comment]
@lance the ec is failing because of high CVEs found in this image, as mentioned above, these are coming from the oc binary, I've tried to use different versions of the oc tool but different versions just generate different high CVE's I think the best thing to do here is to keep ec as optional for access. WDYT?

**Pull request merged**
