### PR TITLE
add-license-file

### PR DESCRIPTION
**Pull request by JasonPowr**
Add the license file to the image, similar to what need to be done for fbc images

### CODE REVIEW

**Comment by JasonPowr** [comment]
I've remove the add, haha never coped that

**Comment by Gregory-Pereira** [comment]
I mean if licenses was the right directory to go in I have no problem with adding it, even if its twice. I was regretting that I didnt have time to fix my lazy copy command

**Comment by JasonPowr** [comment]
```
            {
                "name": "HasLicense",
                "elapsed_time": 0,
                "description": "Checking if terms and conditions applicable to the software including open source licensing information are present. The license must be at /licenses",
                "help": "Check HasLicense encountered an error. Please review the preflight.log file for more information.",
                "suggestion": "Create a directory named /licenses and include all relevant licensing and/or terms and conditions as text file(s) in that directory.",
                "knowledgebase_url": "https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.63/html-single/red_hat_openshift_software_certification_policy_guide/index#assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction",
                "check_url": "https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.63/html-single/red_hat_openshift_software_certification_policy_guide/index#assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction"
            }
```
licenses is the right directory, should be grand

**Comment by JasonPowr** [comment]
Adding it back hah, didn't work for some reason even though it should have been in the same directory

**Pull request merged**
